### ISSUE TITLE
Carthage installation fails with error: no such module 'Rswift'

### ISSUE THREAD

**Issue by Gurpartap** [tomlokhorst/SegueManager#18]
```
$ cat Cartfile

github "tomlokhorst/SegueManager"
```

```
$ carthage update --platform iOS --configuration Release --no-use-binaries --cache-builds

*** Fetching R.swift.Library
*** Fetching SegueManager
*** Checking out SegueManager at "4.0.0"
*** Checking out R.swift.Library at "v4.0.0"
*** xcodebuild output can be found in /var/folders/ly/3f450xdn7g3bjzjdkh7y66tm0000gn/T/carthage-xcodebuild.QJLVVh.log
*** Valid cache found for R.swift.Library, skipping build
*** No cache found for SegueManager, building with all downstream dependencies
*** Building scheme "SegueManager iOS" in SegueManager.xcodeproj
Build Failed

...

/path/to/project/Carthage/Checkouts/SegueManager/src/ios/SegueManager+Rswift.swift:10:8: error: no such module 'Rswift'
import Rswift
       ^

** ARCHIVE FAILED **
```

Also tried `github "mac-cain13/R.swift.Library"` in `/Carthage/Checkouts/SegueManager/Cartfile`, but to no avail; same error (even though `/Carthage/Checkouts/SegueManager/Carthage/Build/iOS/` contains Rswift.framework after the above build attempt)

(I do intend to use SegueManager with R.swift)

**Comment by tomlokhorst** [comment]
Thanks for creating this issue!

I'm not a Carthage user myself, so I'm not too familiar with it.
I tried to fix this by adding R.swift as a dependency via a Cartfile in this repo.

Could you check the feature/carthage branch to see if that works?
`github "tomlokhorst/SegueManager" "feature/carthage"`

If that works correctly for you, I'll merge that feature branch to the main branch.

**Comment by el-hoshino** [comment]
@tomlokhorst hi! Not the original reporter, but I've tried the `feature/carthage` branch, and it seems working under my environment 🎉
